### ISSUE TITLE
Steam Market

### ISSUE THREAD

**Issue by Max0nyM** [DoctorMcKay/node-steamstore#3]
Can We buy with this?

**Comment by andrewda** [comment]
Read the README. Is buying from the market listed as a method? No? Guess you can't buy from the market using this module.

You've opened this issue on many different repositories, and the reason you can't find any modules to buy from the market is because it's against the Steam ToS. That being said, writing your own module to purchase from the market is not at all difficult, and has been done many, many times (just not publicly, because as I said above, it's against the ToS).
